name: model-training
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Data Viz" >> report.md
          echo "### Confusion Matrix" >> report.md
          cml publish ./images/confusion_matrix.png --md >> report.md

          echo "### Feature Importance" >> report.md
          cml publish ./images/feature_importance.png --md >> report.md
          # cat report.md
          cml send-comment report.md
